### ISSUE TITLE
Persistent cache

### ISSUE THREAD

**Issue by fqzz2000** [fqzz2000/SmartSync-Linux#28]
In the current implementation. We delete all local files while we exit the daemon and download all when the process starts, which is a waste of bandwidth. 

We can keep the cache undelete while the daemon exits. 

We also need to persistent the metadata (SyncMap) to rebuild the state.

**Comment by Tenki99** [comment]
1. when booting the program, set all "uploaded" in metadata.json to true
2. update metadata.json when downloading happens
3. modify the "uploaded" in metadata.json to true when uploading finished

**Comment by Tenki99** [comment]
almost finished, will raise merge request with #49 after doing some test tmr morning

**Comment by Tenki99** [comment]
will close after 
1. #53 closed
2. getattr/readdir also moved to modell.py
3. mtime of folder fixed
4. still a problem with download (what if the downloading path not exist)
