### ISSUE TITLE
Enhance the stability of webhook server

### ISSUE THREAD

**Issue by fqzz2000** [fqzz2000/SmartSync-Linux#35]
The webhook server's connection with the client is not stable for the moment. 
Need to enhance the stability of the webhook mechanisms, refactor if necessary.

**Comment by Tenki99** [comment]
Rolled back to the version we demonstrated last week, but still couldn't reproduce the bug. So, I'm going to leave this issue on hold for now. If anyone encounters it again, please report it, or try to figure out the triggering conditions. If none of us encounter it again, or if we encounter it and can't attribute it to anything other than network factors (as we'll the network factor will affect anyway even we adopt ssh, proxy or other methods), we'll then email Tyler to ask what to do next.
