### ISSUE TITLE
Fix bugs in fuselayer interface

### ISSUE THREAD

**Issue by fqzz2000** [fqzz2000/SmartSync-Linux#36]
The fuse layer has a lot of bugs in readdir
Fix and add test cases

**Comment by yuetingLuo** [comment]
[ ] - ls -l 
[ ] - create and write file in file expoler
[ ] - change metadata from list to disc
[ ] - make folder also just a placeholder
[ ] - do not fix metadata.json frequently in writting 
[ ] - use model.py as a function connect dbinterface and fuserlayer

**Comment by yuetingLuo** [comment]
- [ ] rm
- [ ] rename dir
