### ISSUE TITLE
Smart Sync & Synchronization Redesign (high priority)

### ISSUE THREAD

**Issue by fqzz2000** [fqzz2000/SmartSync-Linux#37]
Current smart sync and synchronization are separated e.g. synchronization has no awareness of the metadata.json, and smart sync has its own way of downloading the data. 

A better implementation should be we have an entirely new abstraction (metadata) in the middle. All updates from the servers will only update the metadata and be downloaded to the local cache only when needed. 

The current implementation can be retained as a way for users to to do forced downloading

**Comment by Tenki99** [comment]
new design document
https://docs.google.com/document/d/1QXvYqx8riDxIYKgFDl__F7ihJ0PwS6ERPwivo43991A/edit
