### ISSUE TITLE
debug ls-l problem and mkdir function

### ISSUE THREAD

**Issue by yuetingLuo** [fqzz2000/SmartSync-Linux#59]
Issue when create new file and use 'ls' command

**Comment by fqzz2000** [comment]
current problem: there is a gap between the local update of local_metadata["uploaded"] and remote metadata (which is updated after webhook). It may cause problems in readdir/getattr. During the gap, the file/dir is not considered in the local dir nor in the remote dir.

**Comment by fqzz2000** [comment]
> current problem: there is a gap between the local update of local_metadata["uploaded"] and remote metadata (which is updated after webhook). It may cause problems in readdir/getattr. During the gap, the file/dir is not considered in the local dir nor in the remote dir.

solved

**Comment by fqzz2000** [comment]
here is no mechanism to remove items from local_metadata and .cache
